[build]
  command = "npm install" # Perintah untuk menginstal dependensi (jika ada langkah build lain, tambahkan di sini)
  publish = "public"      # Direktori yang berisi file statis frontend Anda
  functions = "netlify/functions" # Direktori tempat Netlify Functions Anda berada

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api" # Route all /api/* to the root of the api.js function
  status = 200
  force = true # Opsional, memaksa rewrite bahkan jika ada file yang cocok di 'public'

# Jika Anda ingin semua permintaan yang tidak cocok ke file statis diarahkan ke fungsi:
# [[redirects]]
#   from = "/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200